// Generated by Wrangler on Wed Jul 10 2024 01:11:32 GMT+0900 (대한민국 표준시)
// by running `wrangler types`

interface Env {
	LANGCHAIN_TRACING_V2: string;
	LANGCHAIN_ENDPOINT: string;
	LANGCHAIN_API_KEY: string;
	LANGCHAIN_PROJECT: string;
	OPENAI_API_KEY: string;
}
